
// This file is auto-generated by dill-pixel. Do not edit.
import type { initialData, actions, contexts } from '../../dill-pixel.config';
import type { MyApplication } from '@/MyApplication';
// Data
type AppData = typeof initialData;

// Action Contexts
type AppContexts = (typeof contexts)[number];

// Actions
type AppActionMap = typeof actions;
type AppActions = keyof AppActionMap;

// Scenes
type AppScenes = 
  | 'Base'
  | 'start';

// Plugins
type AppPlugins = string;

// Storage adapters
type AppStorageAdapters = string;

/**
 * Add type overrides to the framework
 */
declare module 'dill-pixel' {
  interface AppTypeOverrides {
    App: MyApplication;
    Data: AppData;
    Contexts: AppContexts;
    Actions: AppActions;
    ActionMap: AppActionMap;
    Scenes: AppScenes;
    Plugins: AppPlugins;
    StorageAdapters: AppStorageAdapters;
    Eases: Eases;
  }
}
